const data = {
  cases: [
    {
      id: 1,
      title: "case1",
      img: "/images/cases/corsair.jpg",
      price: 10,
      currency: "USD",
      company: "Corsair",
      inCart: false,
    },
    {
      id: 2,
      title: "case2",
      img: "/images/cases/DIYpc.jpg",
      price: 11,
      currency: "USD",
      company: "Corsair",
      inCart: false,
    },
    {
      id: 3,
      title: "case3",
      img: "/images/cases/NZXT.jpg",
      price: 12,
      currency: "USD",
      company: "Corsair",
      inCart: false,
    },
    {
      id: 4,
      title: "case4",
      img: "/images/cases/rosewill.jpg",
      price: 13,
      currency: "USD",
      company: "Corsair",
      inCart: false,
    },
    {
      id: 5,
      title: "case5",
      img: "/images/cases/thermaltake.jpg",
      price: 14,
      currency: "USD",
      company: "Corsair",
      inCart: false,
    },
  ],
  cpus: [
    {
      id: 1,
      title: "i5 9400",
      img: "/images/cpu/i5 9400.jpeg",
      price: 100,
      currency: "USD",
      company: "intel",
      inCart: false,
    },
    {
      id: 2,
      title: "i5 9600",
      img: "/images/cpu/i5 9600.jpeg",
      price: 110,
      currency: "USD",
      company: "intel",
      inCart: false,
    },
    {
      id: 3,
      title: "i7 8700",
      img: "/images/cpu/i7 8700.jpg",
      price: 120,
      currency: "USD",
      company: "intel",
      inCart: false,
    },
    {
      id: 4,
      title: "i9 9900",
      img: "/images/cpu/i9 9900.png",
      price: 130,
      currency: "USD",
      company: "intel",
      inCart: false,
    },
    {
      id: 5,
      title: "Ryzen 5",
      img: "/images/cpu/ryzen 5.jpeg",
      price: 80,
      currency: "USD",
      company: "intel",
      inCart: false,
    },
    {
      id: 6,
      title: "Ryzen 7",
      img: "/images/cpu/ryzen 7.jpeg",
      price: 90,
      currency: "USD",
      company: "intel",
      inCart: false,
    },
  ],
  cards: [
    {
      id: 1,
      title: "gtx 1070",
      img: "/images/graphic-cards/1.png",
      price: 190,
      currency: "USD",
      company: "evga",
      inCart: false,
    },
    {
      id: 2,
      title: "rtx 2060",
      img: "/images/graphic-cards/2.jpeg",
      price: 290,
      currency: "USD",
      company: "evga",
      inCart: false,
    },
    {
      id: 3,
      title: "rtx 2070",
      img: "/images/graphic-cards/3.png",
      price: 390,
      currency: "USD",
      company: "evga",
      inCart: false,
    },
    {
      id: 4,
      title: "rtx 2070",
      img: "/images/graphic-cards/4.png",
      price: 490,
      currency: "USD",
      company: "evga",
      inCart: false,
    },
    {
      id: 5,
      title: "rtx 2080",
      img: "/images/graphic-cards/5.jpg",
      price: 590,
      currency: "USD",
      company: "evga",
      inCart: false,
    },
  ],
  hardDrives: [
    {
      id: 1,
      title: "Samsung ssd 2tb",
      img: "/images/hard-disk/2tb.jpg",
      price: 200,
      currency: "USD",
      company: "Samsung",
      inCart: false,
    },
    {
      id: 2,
      title: "Samsung ssd 4tb",
      img: "/images/hard-disk/4tb.jpg",
      price: 400,
      currency: "USD",
      company: "Samsung",
      inCart: false,
    },
    {
      id: 3,
      title: "Seagate 1tb",
      img: "/images/hard-disk/seagate1tb.jpg",
      price: 79,
      currency: "USD",
      company: "Seagate",
      inCart: false,
    },
    {
      id: 4,
      title: "Wd Black 1tb",
      img: "/images/hard-disk/wd1tb.jpg",
      price: 89,
      currency: "USD",
      company: "Samsung",
      inCart: false,
    },
    {
      id: 5,
      title: "Samsung ssd 4tb",
      img: "/images/hard-disk/wd1tbssd.jpg",
      price: 400,
      currency: "USD",
      company: "Samsung",
      inCart: false,
    },
  ],
};
export default data;
