export const storeProducts = [
  {
    id: 1,
    title: "case1",
    img: "/images/cases/corsair.jpg",
    price: 10,
    company: "Corsair",
    info: "Lorem ipsum dolor amet offal",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 2,
    title: "case2",
    img: "/images/cases/DIYpc.jpg",
    price: 11,
    company: "Corsair",
    info: "Lorem ipsum dolor amet offal",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 3,
    title: "case3",
    img: "/images/cases/NZXT.jpg",
    price: 12,
    company: "Corsair",
    info: "Lorem ipsum dolor amet offal",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 4,
    title: "case4",
    img: process.env.PUBLIC_URL + "/images/cases/rosewill.jpg",
    price: 13,
    company: "Corsair",
    info: "Lorem ipsum dolor amet offal",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 5,
    title: "case5",
    img: "/images/cases/thermaltake.jpg",
    price: 14,
    company: "Corsair",
    info: "Lorem ipsum dolor amet offal",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 6,
    title: "cpu1",
    img: "/images/cpu/i5 9400.jpg",
    price: 15,
    company: "intel",
    info: "Lorem ipsum dolor amet offal",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 7,
    title: "cpu2",
    img: "/images/cpu/i7 8700.jpg",
    price: 16,
    company: "intel",
    info: "Lorem ipsum dolor amet offal",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 8,
    title: "cpu3",
    img: "/images/cpu/i9 9900.jpg",
    price: 17,
    company: "intel",
    info: "Lorem ipsum dolor amet offal",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 9,
    title: "cpu4",
    img: "/images/cpu/ryzen 5.jpg",
    price: 18,
    company: "Ryzen",
    info: "Lorem ipsum dolor amet offal",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 10,
    title: "cpu5",
    img: "/images/cpu/ryzen 7.jpg",
    price: 19,
    company: "Corsair",
    info: "Lorem ipsum dolor amet offal",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 11,
    title: "card1",
    img: "/images/graphic-cards/evga gtx 1660.jpg",
    price: 20,
    company: "Corsair",
    info: "Lorem ipsum dolor amet offal",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 5,
    title: "case5",
    img: "/images/cases/thermaltake.jpg",
    price: 14,
    company: "Corsair",
    info: "Lorem ipsum dolor amet offal",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 5,
    title: "case5",
    img: "/images/cases/thermaltake.jpg",
    price: 14,
    company: "Corsair",
    info: "Lorem ipsum dolor amet offal",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 5,
    title: "case5",
    img: "/images/cases/thermaltake.jpg",
    price: 14,
    company: "Corsair",
    info: "Lorem ipsum dolor amet offal",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 5,
    title: "case5",
    img: "/images/cases/thermaltake.jpg",
    price: 14,
    company: "Corsair",
    info: "Lorem ipsum dolor amet offal",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 5,
    title: "case5",
    img: "/images/cases/thermaltake.jpg",
    price: 14,
    company: "Corsair",
    info: "Lorem ipsum dolor amet offal",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 5,
    title: "case5",
    img: "/images/cases/thermaltake.jpg",
    price: 14,
    company: "Corsair",
    info: "Lorem ipsum dolor amet offal",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 5,
    title: "case5",
    img: "/images/cases/thermaltake.jpg",
    price: 14,
    company: "Corsair",
    info: "Lorem ipsum dolor amet offal",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 5,
    title: "case5",
    img: "/images/cases/thermaltake.jpg",
    price: 14,
    company: "Corsair",
    info: "Lorem ipsum dolor amet offal",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 5,
    title: "case5",
    img: "/images/cases/thermaltake.jpg",
    price: 14,
    company: "Corsair",
    info: "Lorem ipsum dolor amet offal",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 5,
    title: "case5",
    img: "/images/cases/thermaltake.jpg",
    price: 14,
    company: "Corsair",
    info: "Lorem ipsum dolor amet offal",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 5,
    title: "case5",
    img: "/images/cases/thermaltake.jpg",
    price: 14,
    company: "Corsair",
    info: "Lorem ipsum dolor amet offal",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 5,
    title: "case5",
    img: "/images/cases/thermaltake.jpg",
    price: 14,
    company: "Corsair",
    info: "Lorem ipsum dolor amet offal",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 5,
    title: "case5",
    img: "/images/cases/thermaltake.jpg",
    price: 14,
    company: "Corsair",
    info: "Lorem ipsum dolor amet offal",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 5,
    title: "case5",
    img: "/images/cases/thermaltake.jpg",
    price: 14,
    company: "Corsair",
    info: "Lorem ipsum dolor amet offal",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 5,
    title: "case5",
    img: "/images/cases/thermaltake.jpg",
    price: 14,
    company: "Corsair",
    info: "Lorem ipsum dolor amet offal",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 5,
    title: "case5",
    img: "/images/cases/thermaltake.jpg",
    price: 14,
    company: "Corsair",
    info: "Lorem ipsum dolor amet offal",
    inCart: false,
    count: 0,
    total: 0
  }
];
